/**
 * Development-only sample rows for segmented calendar UI (pass 2).
 * Production builds return an empty list — no fabricated “user” data in prod.
 */

import type { CampaignCalendarEventRecord } from './campaignCalendarArchitecture'

const DEV_FIXTURES: CampaignCalendarEventRecord[] = [
  {
    event_id: 'a1000000-0000-4000-8000-000000000001',
    title: 'Washington County fair — booth',
    event_type: 'public_fair_festival',
    event_subtype: null,
    stage_status: 'approved',
    start_at: '2026-04-26T15:00:00.000Z',
    end_at: '2026-04-26T20:00:00.000Z',
    timezone: 'America/Chicago',
    venue_name: 'County fairgrounds',
    address_or_virtual: null,
    postal_code: '52353',
    owner_user_id: 'coord-alex',
    owner_role: 'event_coordinator',
    host_user_ids: [],
    county_id: 'washington-ia',
    precinct_id: null,
    district_id: null,
    visibility_scope: 'public_visible',
    public_publish_state: null,
    mobilize_publish_state: 'published',
    mobilize_event_id: 'mob_demo_1001',
    mobilize_last_synced_at: '2026-04-02T10:00:00.000Z',
    mobilize_last_error: null,
    mobilize_public_url: 'https://www.mobilize.us/campaignos/example-event/',
    mobilize_tags_synced: true,
    mobilize_sync_hash: 'demo-hash-fair',
    mobilize_update_needed: false,
    mobilize_published_by_user_id: null,
    staffing_state: 'partially_staffed',
    followup_state: null,
    finance_flag: false,
    candidate_flag: true,
    county_party_flag: false,
    public_title: 'Meet us at the Washington County Fair',
    public_description:
      'Volunteer shifts and voter contact at the county fair — family-friendly, public visibility.',
    notes: null,
    created_at: '2026-04-01T12:00:00.000Z',
    updated_at: '2026-04-01T12:00:00.000Z',
  },
  {
    event_id: 'a1000000-0000-4000-8000-000000000002',
    title: 'House party — intro (Cedar Rapids)',
    event_type: 'house_party_intro_candidate',
    event_subtype: null,
    stage_status: 'scheduled',
    start_at: '2026-04-22T23:00:00.000Z',
    end_at: '2026-04-23T01:00:00.000Z',
    timezone: 'America/Chicago',
    venue_name: 'Host residence',
    address_or_virtual: null,
    postal_code: '52401',
    owner_user_id: 'coord-alex',
    owner_role: 'event_coordinator',
    host_user_ids: [],
    county_id: 'linn-ia',
    precinct_id: null,
    district_id: null,
    visibility_scope: 'volunteer_visible',
    public_publish_state: null,
    mobilize_publish_state: 'eligible',
    mobilize_event_id: null,
    mobilize_last_synced_at: null,
    mobilize_last_error: null,
    mobilize_public_url: null,
    mobilize_tags_synced: null,
    mobilize_sync_hash: null,
    mobilize_update_needed: false,
    mobilize_published_by_user_id: null,
    staffing_state: 'staffed',
    followup_state: null,
    finance_flag: false,
    candidate_flag: false,
    county_party_flag: false,
    public_description:
      'Neighbor-hosted intro — meet the campaign team and learn how to plug in before caucus season.',
    public_contact_email: 'hosts@campaignos.example',
    notes: null,
    created_at: '2026-04-01T12:00:00.000Z',
    updated_at: '2026-04-01T12:00:00.000Z',
  },
  {
    event_id: 'a1000000-0000-4000-8000-000000000003',
    title: 'Finance lunch — steering committee',
    event_type: 'lunch_meeting',
    event_subtype: null,
    stage_status: 'approved',
    start_at: '2026-04-24T17:30:00.000Z',
    end_at: '2026-04-24T19:00:00.000Z',
    timezone: 'America/Chicago',
    venue_name: 'Private dining room',
    address_or_virtual: null,
    owner_user_id: 'finance-morgan',
    owner_role: 'finance_lead',
    host_user_ids: [],
    county_id: null,
    precinct_id: null,
    district_id: null,
    visibility_scope: 'finance_private',
    public_publish_state: null,
    mobilize_publish_state: 'not_applicable',
    mobilize_event_id: null,
    mobilize_last_synced_at: null,
    mobilize_last_error: null,
    mobilize_public_url: null,
    mobilize_tags_synced: null,
    mobilize_sync_hash: null,
    mobilize_update_needed: null,
    mobilize_published_by_user_id: null,
    staffing_state: 'staffed',
    followup_state: null,
    finance_flag: true,
    candidate_flag: false,
    county_party_flag: false,
    notes: null,
    created_at: '2026-04-01T12:00:00.000Z',
    updated_at: '2026-04-01T12:00:00.000Z',
  },
  {
    event_id: 'a1000000-0000-4000-8000-000000000004',
    title: 'County party central committee',
    event_type: 'county_party_meeting',
    event_subtype: null,
    stage_status: 'submitted',
    start_at: '2026-05-01T00:00:00.000Z',
    end_at: '2026-05-01T02:00:00.000Z',
    timezone: 'America/Chicago',
    venue_name: 'Party HQ',
    address_or_virtual: null,
    owner_user_id: 'county-jordan',
    owner_role: 'county_lead',
    host_user_ids: [],
    county_id: 'johnson-ia',
    precinct_id: null,
    district_id: null,
    visibility_scope: 'field_team',
    public_publish_state: null,
    mobilize_publish_state: 'queued',
    mobilize_event_id: null,
    mobilize_last_synced_at: null,
    mobilize_last_error: null,
    mobilize_public_url: null,
    mobilize_tags_synced: null,
    mobilize_sync_hash: null,
    mobilize_update_needed: false,
    mobilize_published_by_user_id: null,
    staffing_state: 'unstaffed',
    followup_state: null,
    finance_flag: false,
    candidate_flag: false,
    county_party_flag: true,
    notes: null,
    created_at: '2026-04-01T12:00:00.000Z',
    updated_at: '2026-04-01T12:00:00.000Z',
  },
  {
    event_id: 'a1000000-0000-4000-8000-000000000005',
    title: 'Spring rally — downtown',
    event_type: 'campaign_rally',
    event_subtype: null,
    stage_status: 'scheduled',
    start_at: '2026-05-10T19:00:00.000Z',
    end_at: '2026-05-10T21:00:00.000Z',
    timezone: 'America/Chicago',
    venue_name: 'City plaza',
    address_or_virtual: null,
    postal_code: '52240',
    owner_user_id: 'coord-alex',
    owner_role: 'event_coordinator',
    host_user_ids: [],
    county_id: null,
    precinct_id: null,
    district_id: 'ia-01',
    visibility_scope: 'public_visible',
    public_publish_state: null,
    mobilize_publish_state: 'sync_error',
    mobilize_event_id: 'mob_demo_1005',
    mobilize_last_synced_at: '2026-04-10T08:00:00.000Z',
    mobilize_last_error:
      'Example error string only — no Mobilize API call runs in this build. Check server logs when wired.',
    mobilize_public_url: null,
    mobilize_tags_synced: false,
    mobilize_sync_hash: 'demo-hash-rally-stale',
    mobilize_update_needed: true,
    mobilize_published_by_user_id: null,
    staffing_state: 'at_risk',
    followup_state: null,
    finance_flag: false,
    candidate_flag: true,
    county_party_flag: false,
    notes: null,
    created_at: '2026-04-01T12:00:00.000Z',
    updated_at: '2026-04-01T12:00:00.000Z',
  },
  {
    event_id: 'a1000000-0000-4000-8000-000000000006',
    title: 'Volunteer coffee — downtown',
    event_type: 'coffee_meeting',
    event_subtype: null,
    stage_status: 'draft',
    start_at: '2026-04-20T14:00:00.000Z',
    end_at: '2026-04-20T15:00:00.000Z',
    timezone: 'America/Chicago',
    venue_name: 'Café meetup',
    address_or_virtual: null,
    owner_user_id: 'vol-ops-taylor',
    owner_role: 'volunteer_coordinator',
    host_user_ids: [],
    county_id: null,
    precinct_id: null,
    district_id: null,
    visibility_scope: 'internal_staff',
    public_publish_state: null,
    mobilize_publish_state: 'not_applicable',
    mobilize_event_id: null,
    mobilize_last_synced_at: null,
    mobilize_last_error: null,
    mobilize_public_url: null,
    mobilize_tags_synced: null,
    mobilize_sync_hash: null,
    mobilize_update_needed: null,
    mobilize_published_by_user_id: null,
    staffing_state: 'partially_staffed',
    followup_state: null,
    finance_flag: false,
    candidate_flag: false,
    county_party_flag: false,
    notes: null,
    created_at: '2026-04-01T12:00:00.000Z',
    updated_at: '2026-04-01T12:00:00.000Z',
  },
]

export function getDevCalendarFixtureEvents(): CampaignCalendarEventRecord[] {
  if (!import.meta.env.DEV) return []
  return DEV_FIXTURES
}

export function getDevCalendarEventById(
  eventId: string,
): CampaignCalendarEventRecord | null {
  if (!import.meta.env.DEV) return null
  return DEV_FIXTURES.find((e) => e.event_id === eventId) ?? null
}
