/** Canonical metric keys — first-truth set (Phase 1). */
export const COP_METRIC_KEYS = [
  'upcoming_event_volume_7d',
  'critical_events_understaffed',
  'events_missing_run_of_show',
  'events_missing_comms_plan',
  'events_missing_after_action',
  'event_execution_readiness_score',
  'open_staffing_slots',
  'volunteer_fill_rate',
  'high_priority_opportunities_unclaimed',
  'volunteer_response_velocity',
  'volunteer_capacity_pressure',
  'approval_backlog_total',
  'approval_backlog_over_sla',
  'blocked_event_publish_count',
  'governance_intervention_count',
  'open_critical_tasks',
  'overdue_operational_tasks',
  'task_completion_velocity',
  'unresolved_exception_requests',
  'overall_operational_readiness',
  'campaign_pressure_index',
  'campaign_momentum_index',
  'data_freshness_score',
] as const

export type CopMetricKey = (typeof COP_METRIC_KEYS)[number]

export const COP_METRIC_LABELS: Record<string, string> = {
  upcoming_event_volume_7d: 'Events (next 7 days)',
  critical_events_understaffed: 'Critical risk events',
  events_missing_run_of_show: 'Events missing run-of-show',
  events_missing_comms_plan: 'Events with comms gaps',
  events_missing_after_action: 'After-action gaps',
  event_execution_readiness_score: 'Event execution readiness',
  open_staffing_slots: 'Open staffing slots (proxy)',
  volunteer_fill_rate: 'Volunteer fill rate',
  high_priority_opportunities_unclaimed: 'Urgent opportunities',
  volunteer_response_velocity: 'Volunteer response velocity',
  volunteer_capacity_pressure: 'Volunteer capacity pressure',
  approval_backlog_total: 'Pending approvals',
  approval_backlog_over_sla: 'Approvals over SLA (proxy)',
  blocked_event_publish_count: 'Blocked publishes',
  governance_intervention_count: 'Governance interventions',
  open_critical_tasks: 'Open critical tasks',
  overdue_operational_tasks: 'Overdue tasks',
  task_completion_velocity: 'Task velocity',
  unresolved_exception_requests: 'Unresolved exceptions',
  overall_operational_readiness: 'Operational readiness',
  campaign_pressure_index: 'Campaign pressure',
  campaign_momentum_index: 'Campaign momentum',
  data_freshness_score: 'Data freshness',
}
