/**
 * Interactive bootstrap for `.env` (local only; never commit).
 * Does not echo saved secrets; only length / "set" status after write.
 */
import fs from 'node:fs'
import path from 'node:path'
import readline from 'node:readline/promises'
import { stdin as input, stdout as output } from 'node:process'

const root = path.resolve(import.meta.dirname, '..')
const envPath = path.join(root, '.env')

/** @type {{ key: string, clientSafe: boolean }[]} */
const KEYS = [
  { key: 'VITE_SUPABASE_URL', clientSafe: true },
  { key: 'VITE_SUPABASE_ANON_KEY', clientSafe: true },
  { key: 'OPENAI_API_KEY', clientSafe: false },
  { key: 'SENDGRID_API_KEY', clientSafe: false },
  { key: 'TWILIO_ACCOUNT_SID', clientSafe: false },
  { key: 'TWILIO_AUTH_TOKEN', clientSafe: false },
  { key: 'TWILIO_PHONE_NUMBER', clientSafe: false },
]

const PLACEHOLDER_HINTS = [
  'your_url',
  'your_key',
  'your_supabase',
  'your-project',
  'changeme',
  'replace_me',
]

function isPlaceholder(value, key) {
  const v = value.trim().toLowerCase()
  if (!v) return true
  if (PLACEHOLDER_HINTS.some((p) => v.includes(p))) return true
  if (key === 'VITE_SUPABASE_URL' && !v.startsWith('http')) return true
  return false
}

function parseEnvFile(content) {
  /** @type {Map<string, string>} */
  const map = new Map()
  for (const line of content.split('\n')) {
    const t = line.trim()
    if (!t || t.startsWith('#')) continue
    const eq = t.indexOf('=')
    if (eq === -1) continue
    const k = t.slice(0, eq).trim()
    let val = t.slice(eq + 1).trim()
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1).replace(/\\n/g, '\n').replace(/\\"/g, '"')
    }
    map.set(k, val)
  }
  return map
}

function escapeEnvValue(val) {
  if (val === '') return ''
  if (/[\r\n"#\s]/.test(val)) {
    return `"${val.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
  }
  return val
}

function formatEnv(map) {
  const lines = [
    '# Generated by scripts/setup-env.mjs — do not commit.',
    '# Client (VITE_* is exposed to the browser; use public anon key + RLS).',
    '',
  ]
  for (const { key, clientSafe } of KEYS) {
    if (!clientSafe && lines[lines.length - 1] !== '') {
      lines.push('', '# Server-only (never prefix with VITE_; not for client code).', '')
    }
    const v = map.get(key) ?? ''
    lines.push(`${key}=${escapeEnvValue(v)}`)
  }
  lines.push('')
  return lines.join('\n')
}

function describeSet(key, value) {
  if (!value.trim()) return `${key}: (empty)`
  return `${key}: set (${value.length} characters)`
}

async function main() {
  const rl = readline.createInterface({ input, output })

  let existing = new Map()
  if (fs.existsSync(envPath)) {
    existing = parseEnvFile(fs.readFileSync(envPath, 'utf8'))
    output.write(`\nFound existing ${path.basename(envPath)}.\n`)
  } else {
    output.write(`\nCreating ${path.basename(envPath)}.\n`)
  }

  const next = new Map(existing)

  try {
    for (const { key, clientSafe } of KEYS) {
      const current = next.get(key) ?? ''
      const hasConcrete =
        current.length > 0 && !isPlaceholder(current, key)

      if (hasConcrete) {
        const ans = (
          await rl.question(
            `${key} already has a value. Overwrite? [y/N]: `,
          )
        ).trim()
        if (ans.toLowerCase() !== 'y' && ans.toLowerCase() !== 'yes') {
          output.write(`  Keeping existing ${key} (${current.length} chars).\n`)
          continue
        }
      }

      const tag = clientSafe ? 'client-safe' : 'server-only (never VITE_)'
      output.write(`\n${key} [${tag}] — paste value (input may be visible in terminal).\n`)
      const entered = (await rl.question('> ')).trim()
      next.set(key, entered)
    }
  } finally {
    rl.close()
  }

  fs.writeFileSync(envPath, formatEnv(next), 'utf8')
  output.write(`\nWrote ${envPath}\n`)
  output.write('Summary (not full secrets):\n')
  for (const { key } of KEYS) {
    output.write(`  ${describeSet(key, next.get(key) ?? '')}\n`)
  }
  output.write('\nDone.\n')
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
